/*
 Navicat Premium Data Transfer

 Source Server         : awm2023
 Source Server Type    : PostgreSQL
 Source Server Version : 130003
 Source Host           : localhost:25432
 Source Catalog        : gis
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130003
 File Encoding         : 65001

 Date: 22/10/2022 18:44:46
*/


-- ----------------------------
-- Table structure for awm2023_profile
-- ----------------------------
DROP TABLE IF EXISTS "public"."awm2023_profile";
CREATE TABLE "public"."awm2023_profile" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "created" timestamptz(6) NOT NULL,
  "modified" timestamptz(6) NOT NULL,
  "last_location" geometry(POINT, 4326),
  "user_id" int4 NOT NULL
)
;

-- ----------------------------
-- Records of awm2023_profile
-- ----------------------------
INSERT INTO "public"."awm2023_profile" VALUES (1, '2022-10-18 13:52:31.651098+00', '2022-10-22 17:03:12.75792+00', '0101000020E61000007978CF81E50819C0AC3C81B053AC4A40', 1);

-- ----------------------------
-- Auto increment value for awm2023_profile
-- ----------------------------
SELECT setval('"public"."awm2023_profile_id_seq"', 1, true);

-- ----------------------------
-- Indexes structure for table awm2023_profile
-- ----------------------------
CREATE INDEX "awm2023_profile_last_location_944e9aa9_id" ON "public"."awm2023_profile" USING gist (
  "last_location" "public"."gist_geometry_ops_2d"
);

-- ----------------------------
-- Uniques structure for table awm2023_profile
-- ----------------------------
ALTER TABLE "public"."awm2023_profile" ADD CONSTRAINT "awm2023_profile_user_id_key" UNIQUE ("user_id");

-- ----------------------------
-- Primary Key structure for table awm2023_profile
-- ----------------------------
ALTER TABLE "public"."awm2023_profile" ADD CONSTRAINT "awm2023_profile_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table awm2023_profile
-- ----------------------------
ALTER TABLE "public"."awm2023_profile" ADD CONSTRAINT "awm2023_profile_user_id_d107a9ef_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "public"."auth_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
